export class Crypto {
  _id: string;
  date: Date;
  cryptoName : string;
  cryptoCurrency : string;
  type : string;
  market : string;
  fromSymbol: string;
  toSymbol : string;
  flags : string;
  price : string;
  lastUpdatde : number;
  median : number;
  lastVolume: number;
  lastVolumeto : number;
  lastTradedid : string;
  volumeDay : number;
  volumeDayTo : number;
  volume24Hour : number;
  volume24HourTo : number;
  openDay : number;
  highDay : number;
  lowDay : number;
  open24Hour : number;
  high24Hour : number;
  low24Hour : number;
  lastMarket : string;
  volumeHour: number;
  volumeHourTo : number;
  openHour : number;
  highHour : number;
  lowHour : number;
  topTierVolume24Hour : number;
  topTierVolume24HourTo : number;
  change24Hour : number;
  change24PCT24Hour : number;
  changeDay : number;
  changePCTDay : number;
  changeHour : number;
  changePCTHour : number;
  conversionType : string;
  conversionSymbol : string;
  supply : number;
  MKTCAP : number;
  MKTCAPPenalty : number;
  circulationSupply : number;
  circulationSupplyMKTCAP : number;
  totalVolume24H : number;
  totalVolume24HTo : number;
  totalToptierVolume24H: number;
  totalToptierVolume24HTo : number;
  imageUrl : string
}
